version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "10079:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
  app1:
    image: myflaskapp
    container_name: app1
    ports:
      - "5001:5000"
